### ISSUE TITLE
Not compiling with TeX Live Ubuntu package

### ISSUE THREAD

**Issue by msz** [sebastianzillessen/KCLInformaticsMScProjectLayout#1]
Compiling with `pdflatex` gives the error

```
LaTeX Error: File `MnSymbol.sty' not found.
```

I'm using the TeX Live Ubuntu package version `2015.20150625-1ubuntu1`.

**Comment by hmmmsausages** [comment]
Hi this is possibly because your TeX distribution hasn't got the MnSymbol.sty class installed.
You can download it [here](http://anorien.csc.warwick.ac.uk/mirrors/CTAN/help/Catalogue/entries/mnsymbol.html).
Hope this helps.
