### ISSUE TITLE
Project doesn't compile

### ISSUE THREAD

**Issue by czechboy0** [sebastianzillessen/KCLInformaticsMScProjectLayout#4]
Hi @sebastianzillessen,

I just cloned the template, but unfortunately the way it is it doesn't compile with `pdflatex Thesis.tex`. See attached log.
[pdflatex.txt](https://github.com/sebastianzillessen/KCLInformaticsMScProjectLayout/files/229737/pdflatex.txt)

**Comment by sebastianzillessen** [comment]
Hi, 

Thanks for contributing.
According to your log, the glossary entry for Linux hasn't been defined. Seems like we removed something which is still needed. 
You can either try to fix it by removing the Glspl{Linux} in main.tex or wait till I check it again, which will not happen before tomorrow!

**Comment by czechboy0** [comment]
That's fine, I'll wait till tomorrow. I'd like to have a template which can properly handle glossary terms for my thesis :) 

Thanks for publishing this!

**Comment by sebastianzillessen** [comment]
Ah, is it possible that you didn't run the `make index`and the `bibtex` commands?

```
xelatex -file-line-error -interaction=nonstopmode Thesis.tex
bibtex Thesis
makeindex Thesis.acn 
makeindex Thesis.glo 
xelatex Thesis.tex
```

are the commands you need to run from the terminal. 

I would recommend to use Texpad (https://www.texpadapp.com/) for your thesis, yes it is not free, but it is so much easier to work with that, than in plain editors...

I could compile it with these commands, therefore I'm closing the issue.

**Comment by czechboy0** [comment]
@sebastianzillessen Thanks for the tip, TextPad looks amazing! Yes you're right, I didn't compile the references first, apologies.
