### ISSUE TITLE
Declaration displays as part of the last section of the document

### ISSUE THREAD

**Issue by msz** [sebastianzillessen/KCLInformaticsMScProjectLayout#5]
[Screenshot](http://i.imgur.com/RWc4avK.png)

Do you know how to fix it? I looked around but couldn't figure out anything.

**Comment by hmmmsausages** [comment]
You have to edit the "Thesis.tex" file and just put the `\include{structure/declaration}` line (currently at line 89) at the position you would like it to appear. 
For example before the `\include{contents/introduction}` (at line 70), so it will appear before the introduction.

**Comment by msz** [comment]
I wanted to keep it at the end and remove the header with "References" because I thought that's the suggested structure, but now I see that the declaration is not in the suggested structure anywhere. So I guess moving it to the front is a good solution. Thanks.
