### ISSUE TITLE
Alignment in title page.

### ISSUE THREAD

**Issue by freshn** [sebastianzillessen/KCLInformaticsMScProjectLayout#6]
@sebastianzillessen Above all, thank you so much for making such a wonderful LaTeX template. I believe it would help amounts of students at KCL Informatics.

However, I have some troubles about the official styled title page. The problem is that when the report's title is too long，the aligemnet at row 'Project Title' looks a little werid and 'Signture' would move to a new page. It looks like the following image.
![kclinformatics](https://user-images.githubusercontent.com/27129365/83726675-c8c73080-a63b-11ea-8c5c-a42951a080c3.png)

Is it possible to fix this issue?

**Comment by sebastianzillessen** [comment]
Jo @freshn . 

Great to hear that you are using the Template. 
I'm not at King's anymore and unfortunately I do not have the time to fix this issue, but I am sure you can accept the challenge and fix it yourself ☺️ 

Looking forward for your PR to provide the fix to all other users of the template! 

All the best, 
Sebastian
